# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TelaCadastro.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TelaCadastro(object):
    def setupUi(self, TelaCadastro):
        TelaCadastro.setObjectName(_fromUtf8("TelaCadastro"))
        TelaCadastro.resize(800, 600)
        self.centralwidget = QtGui.QWidget(TelaCadastro)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 80, 61, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(560, 80, 61, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 160, 41, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 240, 61, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(450, 240, 61, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(320, 160, 91, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.lineEditNome = QtGui.QLineEdit(self.centralwidget)
        self.lineEditNome.setGeometry(QtCore.QRect(90, 70, 421, 27))
        self.lineEditNome.setObjectName(_fromUtf8("lineEditNome"))
        self.lineEditIdade = QtGui.QLineEdit(self.centralwidget)
        self.lineEditIdade.setGeometry(QtCore.QRect(620, 70, 151, 27))
        self.lineEditIdade.setObjectName(_fromUtf8("lineEditIdade"))
        self.lineEditCPF = QtGui.QLineEdit(self.centralwidget)
        self.lineEditCPF.setGeometry(QtCore.QRect(70, 150, 211, 27))
        self.lineEditCPF.setFrame(True)
        self.lineEditCPF.setCursorPosition(0)
        self.lineEditCPF.setObjectName(_fromUtf8("lineEditCPF"))
        self.lineEditEndereco = QtGui.QLineEdit(self.centralwidget)
        self.lineEditEndereco.setGeometry(QtCore.QRect(410, 150, 361, 27))
        self.lineEditEndereco.setObjectName(_fromUtf8("lineEditEndereco"))
        self.lineEditLogin = QtGui.QLineEdit(self.centralwidget)
        self.lineEditLogin.setGeometry(QtCore.QRect(90, 230, 301, 27))
        self.lineEditLogin.setObjectName(_fromUtf8("lineEditLogin"))
        self.lineEditSenha = QtGui.QLineEdit(self.centralwidget)
        self.lineEditSenha.setGeometry(QtCore.QRect(510, 230, 261, 27))
        self.lineEditSenha.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEditSenha.setObjectName(_fromUtf8("lineEditSenha"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(270, 270, 251, 251))
        self.label_7.setText(_fromUtf8(""))
        self.label_7.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../Downloads/PARA REDES/cadas.png")))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.pushButtonCadastrar = QtGui.QPushButton(self.centralwidget)
        self.pushButtonCadastrar.setGeometry(QtCore.QRect(560, 500, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonCadastrar.setFont(font)
        self.pushButtonCadastrar.setObjectName(_fromUtf8("pushButtonCadastrar"))
        self.pushButtonSair = QtGui.QPushButton(self.centralwidget)
        self.pushButtonSair.setGeometry(QtCore.QRect(70, 500, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonSair.setFont(font)
        self.pushButtonSair.setObjectName(_fromUtf8("pushButtonSair"))
        self.pushButtonInicio = QtGui.QPushButton(self.centralwidget)
        self.pushButtonInicio.setGeometry(QtCore.QRect(0, 0, 98, 27))
        self.pushButtonInicio.setObjectName(_fromUtf8("pushButtonInicio"))
        TelaCadastro.setCentralWidget(self.centralwidget)
        self.actionInicio = QtGui.QAction(TelaCadastro)
        self.actionInicio.setObjectName(_fromUtf8("actionInicio"))
        self.actionSair = QtGui.QAction(TelaCadastro)
        self.actionSair.setObjectName(_fromUtf8("actionSair"))
        self.actionCadastro = QtGui.QAction(TelaCadastro)
        self.actionCadastro.setObjectName(_fromUtf8("actionCadastro"))
        self.actionLogin = QtGui.QAction(TelaCadastro)
        self.actionLogin.setObjectName(_fromUtf8("actionLogin"))

        self.retranslateUi(TelaCadastro)
        QtCore.QObject.connect(self.pushButtonCadastrar, QtCore.SIGNAL(_fromUtf8("clicked()")), TelaCadastro.cadastrar)
        QtCore.QObject.connect(self.pushButtonSair, QtCore.SIGNAL(_fromUtf8("clicked()")), TelaCadastro.sairCadastro)
        QtCore.QObject.connect(self.pushButtonInicio, QtCore.SIGNAL(_fromUtf8("clicked()")), TelaCadastro.inicio)
        QtCore.QMetaObject.connectSlotsByName(TelaCadastro)

    def retranslateUi(self, TelaCadastro):
        TelaCadastro.setWindowTitle(_translate("TelaCadastro", "Cadastro", None))
        self.label.setText(_translate("TelaCadastro", "Nome:", None))
        self.label_2.setText(_translate("TelaCadastro", "Idade:", None))
        self.label_3.setText(_translate("TelaCadastro", "CPF:", None))
        self.label_4.setText(_translate("TelaCadastro", "Login:", None))
        self.label_5.setText(_translate("TelaCadastro", "Senha:", None))
        self.label_6.setText(_translate("TelaCadastro", "Endereço:", None))
        self.lineEditCPF.setInputMask(_translate("TelaCadastro", "###.###.###-##; ", None))
        self.lineEditCPF.setText(_translate("TelaCadastro", "..--", None))
        self.pushButtonCadastrar.setText(_translate("TelaCadastro", "Cadastrar", None))
        self.pushButtonSair.setText(_translate("TelaCadastro", "Sair", None))
        self.pushButtonInicio.setText(_translate("TelaCadastro", "Início", None))
        self.actionInicio.setText(_translate("TelaCadastro", "Inicio", None))
        self.actionSair.setText(_translate("TelaCadastro", "Sair", None))
        self.actionCadastro.setText(_translate("TelaCadastro", "Cadastro", None))
        self.actionLogin.setText(_translate("TelaCadastro", "Login", None))


