# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TelaApostar.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TelaApostar(object):
    def setupUi(self, TelaApostar):
        TelaApostar.setObjectName(_fromUtf8("TelaApostar"))
        TelaApostar.resize(800, 600)
        self.centralwidget = QtGui.QWidget(TelaApostar)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.pushButtonInicio = QtGui.QPushButton(self.centralwidget)
        self.pushButtonInicio.setGeometry(QtCore.QRect(0, 0, 98, 27))
        self.pushButtonInicio.setObjectName(_fromUtf8("pushButtonInicio"))
        self.lineEdit01 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit01.setGeometry(QtCore.QRect(70, 310, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(31)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit01.setFont(font)
        self.lineEdit01.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit01.setObjectName(_fromUtf8("lineEdit01"))
        self.lineEdit02 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit02.setGeometry(QtCore.QRect(190, 310, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(31)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit02.setFont(font)
        self.lineEdit02.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit02.setObjectName(_fromUtf8("lineEdit02"))
        self.lineEdit03 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit03.setGeometry(QtCore.QRect(310, 310, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(31)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit03.setFont(font)
        self.lineEdit03.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit03.setObjectName(_fromUtf8("lineEdit03"))
        self.lineEdit04 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit04.setGeometry(QtCore.QRect(430, 310, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(31)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit04.setFont(font)
        self.lineEdit04.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit04.setObjectName(_fromUtf8("lineEdit04"))
        self.lineEdit05 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit05.setGeometry(QtCore.QRect(550, 310, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(31)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit05.setFont(font)
        self.lineEdit05.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit05.setObjectName(_fromUtf8("lineEdit05"))
        self.lineEdit06 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit06.setGeometry(QtCore.QRect(670, 310, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(31)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit06.setFont(font)
        self.lineEdit06.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit06.setObjectName(_fromUtf8("lineEdit06"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 70, 321, 101))
        font = QtGui.QFont()
        font.setPointSize(72)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(260, 230, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.pushButtonApostar = QtGui.QPushButton(self.centralwidget)
        self.pushButtonApostar.setGeometry(QtCore.QRect(70, 440, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonApostar.setFont(font)
        self.pushButtonApostar.setObjectName(_fromUtf8("pushButtonApostar"))
        self.pushButtonCancelar = QtGui.QPushButton(self.centralwidget)
        self.pushButtonCancelar.setGeometry(QtCore.QRect(550, 440, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonCancelar.setFont(font)
        self.pushButtonCancelar.setObjectName(_fromUtf8("pushButtonCancelar"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 570, 151, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(400, 570, 371, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        TelaApostar.setCentralWidget(self.centralwidget)
        self.actionIn_cio = QtGui.QAction(TelaApostar)
        self.actionIn_cio.setObjectName(_fromUtf8("actionIn_cio"))
        self.actionSair = QtGui.QAction(TelaApostar)
        self.actionSair.setObjectName(_fromUtf8("actionSair"))
        self.actionComo_Apostar = QtGui.QAction(TelaApostar)
        self.actionComo_Apostar.setObjectName(_fromUtf8("actionComo_Apostar"))

        self.retranslateUi(TelaApostar)
        QtCore.QObject.connect(self.pushButtonInicio, QtCore.SIGNAL(_fromUtf8("clicked()")), TelaApostar.inicio)
        QtCore.QObject.connect(self.pushButtonApostar, QtCore.SIGNAL(_fromUtf8("clicked()")), TelaApostar.apostar)
        QtCore.QObject.connect(self.pushButtonCancelar, QtCore.SIGNAL(_fromUtf8("clicked()")), TelaApostar.inicio)
        QtCore.QMetaObject.connectSlotsByName(TelaApostar)

    def retranslateUi(self, TelaApostar):
        TelaApostar.setWindowTitle(_translate("TelaApostar", "Apostas", None))
        self.pushButtonInicio.setText(_translate("TelaApostar", "Início", None))
        self.lineEdit01.setInputMask(_translate("TelaApostar", "##; ", None))
        self.lineEdit02.setInputMask(_translate("TelaApostar", "##; ", None))
        self.lineEdit03.setInputMask(_translate("TelaApostar", "##; ", None))
        self.lineEdit04.setInputMask(_translate("TelaApostar", "##; ", None))
        self.lineEdit05.setInputMask(_translate("TelaApostar", "##; ", None))
        self.lineEdit06.setInputMask(_translate("TelaApostar", "##; ", None))
        self.label.setText(_translate("TelaApostar", "Loteria", None))
        self.label_2.setText(_translate("TelaApostar", "Faça o seu jogo", None))
        self.pushButtonApostar.setText(_translate("TelaApostar", "Apostar", None))
        self.pushButtonCancelar.setText(_translate("TelaApostar", "Cancelar", None))
        self.label_3.setText(_translate("TelaApostar", "Valor do jogo: R$ 2,00", None))
        self.label_4.setText(_translate("TelaApostar", "Cada jogo realizado será debitado no cartão de créditos.", None))
        self.actionIn_cio.setText(_translate("TelaApostar", "Início", None))
        self.actionSair.setText(_translate("TelaApostar", "Sair", None))
        self.actionComo_Apostar.setText(_translate("TelaApostar", "Como Apostar", None))
